[package]
name = "Advent-of-Code-2023"
authors = ["Nicklas Vedsted"]
description = "Advent of Code 2023 implementation"
repository = "https://github.com/NVedsted/Advent-of-Code-2023"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
